---
# BOSSBAR CONFIGURATION #
# ===================== #
head-message: "BossBar"
changing-messages:
- "{100%} Message 1"
- "{80%} Message 2"
- "{60%} Message 3"
- "{40%} Message 4"
- "{20%} Message 5"
change-speed: 8
worlds: []
...
